# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuessWord' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuessWord
  pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
        pod 'Firebase/Database'
  pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseFirestoreSwift'

  
  plugin 'cocoapods-keys', {
  :project => "GuessWord",
  :target => "GuessWord",
  :keys => [
    "WordnikAPIKey",
    "CorrectKey"
  ]
}
end
